### ISSUE TITLE
Blurb for webpage

### ISSUE THREAD

**Issue by JensMNielsen** [MattCallahan-NOAA/ESR-ESP#3]
Blurb for VIIRS shiny: Still needs to be corrected too. 

Weekly averaged satellite Chl-a estimates from near-real time VIIRS for each of the ecosystem regions managed by the Alaska Fisheries Science Center. Near real-time chla data are preliminary estimates that have yet to be fully quality controlled. For better visualization the Chl-a color scale is log-transformed and maximum Chl-a scale is set to a maximum of 15 ug/l. 

Chl-a are updated automatically using satellite data curated by NOAA's Coast Watch Program, while ice fraction data are updated automatically using satellite data curated by NOAA's Coral Reef Watch Program. 

**Images**: description: Spatial chla and ice data for the Bering Sea from the most recent week (bottom right) and preceeding weeks. Images were chosen based on the fewest missing pixels for each period leaving eat least 5 days between images. 

**Timeseries**: The current year's daily temperatures (black lines) are compared to the previous year (blue line), the daily average (2013-2022, purple), and each of the individual years since 2013 (grey lines).

ALSO add: Last updated: XX-XX-XXXX

**Comment by MattCallahan-NOAA** [comment]
Done, dates are in plot titles.

**Comment by MattCallahan-NOAA** [comment]
Done, dates are in plot titles.
